version: "3.7"
services:
  dockerproxy:
    container_name: jamdev_dockerproxy 
    image: tecnativa/docker-socket-proxy
    environment:
      CONTAINERS: 1
    privileged: true 
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:z"
  traefik:
    container_name: jamdev_gateway
    image: "traefik:v2.4.8"
    restart: always
    depends_on:
      - dockerproxy
    ports:
      - "80:80"
      - "8080:8080"
        #      - "3000:3000"
      - "443:443"
    volumes:
      - "./.traefik/config.toml:/etc/traefik/traefik.toml:ro,z"
      - "./.traefik/dynamic:/etc/traefik/dynamic:ro,z"
      - "./.certs:/.certs:ro,z"
    labels:
      - "traefik.http.routers.traefik.rule=Host(`jamdev.test`)"
      - "traefik.http.routers.traefik.service=traefik-svc"
      - "traefik.http.services.traefik-svc.loadBalancer.server.port=8080"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.enable=true"
  sftp:
    container_name: jamdev_sftp
    image: atmoz/sftp
    volumes:
      - ./sftp_data:/home/jamdev/logos:z
    ports:
        - "2223:22"
    command: jamdev:jamdev:1000
  minio:
    container_name: jamdev_minio 
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_DOMAIN: storage.jamdev.test
    command: server /data --console-address ":9001"
    volumes:
      - "minio_data:/data"
    labels:
        # MINIO ADMIN
      - "traefik.http.routers.jamdev-minio-admin.rule=Host(`minio.jamdev.test`)"
      - "traefik.http.routers.jamdev-minio-admin.service=jamdev-minio-admin-svc"
      - "traefik.http.services.jamdev-minio-admin-svc.loadBalancer.server.port=9001"
      - "traefik.http.routers.jamdev-minio-admin.tls=true"
        # MINIO VIRTUAL BUCKET ACCESS
      - "traefik.http.routers.jamdev-minio.rule=HostRegexp(`{subhost:[a-z-]+}.storage.jamdev.test`)"
      - "traefik.http.routers.jamdev-minio.service=jamdev-minio-svc"
      - "traefik.http.services.jamdev-minio-svc.loadBalancer.server.port=9000"
      - "traefik.http.routers.jamdev-minio.tls=true"
      - "traefik.enable=true"
  mail:
    image: "mailhog/mailhog:v1.0.1"
    container_name: jamdev_mail
    restart: always
    environment:
      - MH_STORAGE=maildir
      - MH_MAILDIR_PATH=/home/mailhog/maildir
    labels:
      - "traefik.http.routers.mailhog.rule=Host(`mail.jamdev.test`)"
      - "traefik.http.routers.mailhog.tls=true"
      - "traefik.http.routers.mailhog.service=mailhog-svc"
      - "traefik.http.services.mailhog-svc.loadBalancer.server.port=8025"
      - "traefik.enable=true"
    ports:
      - "1025:1025"
  docker-host:
    image: "qoomon/docker-host:2.7.0"
    cap_add: ["NET_ADMIN", "NET_RAW"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
  docker-ssh:
    image: panubo/sshd
    environment: 
      - SSH_USERS=jamdev:1001:1001
      - SSH_ENABLE_PASSWORD_AUTH=true
      - TCP_FORWARDING=true
    volumes:
      - "./ssh/bootstrap/:/etc/entrypoint.d/"
    ports:
      - "32220:22"
    labels:
      - "traefik.enable=false"
volumes:
  minio_data:
  sftp_data:
networks:
  default:
    external:
      name: jamdev
