version: "3.7"
services:
  traefik:
    container_name: jamdev_gateway
    image: "traefik:v2.2"
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./.traefik/config.toml:/etc/traefik/traefik.toml:ro"
      - "./.traefik/dynamic:/etc/traefik/dynamic:ro"
      - "./.certs:/.certs:ro"
    labels:
      - "traefik.http.routers.traefik.rule=Host(`jamdev.test`)"
      - "traefik.http.routers.traefik.service=traefik-svc"
      - "traefik.http.services.traefik-svc.loadBalancer.server.port=8080"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.enable=true"
  mail:
    image: mailhog/mailhog
    restart: always
    environment:
      - MH_STORAGE=maildir
      - MH_MAILDIR_PATH=/home/mailhog/maildir
    labels:
      - "traefik.http.routers.mailhog.rule=Host(`mail.jamdev.test`)"
      - "traefik.http.routers.mailhog.tls=true"
      - "traefik.http.routers.mailhog.service=mailhog-svc"
      - "traefik.http.services.mailhog-svc.loadBalancer.server.port=8025"
      - "traefik.enable=true"
    ports:
      - "1025:1025"
  docker-host:
    image: qoomon/docker-host
    cap_add: ["NET_ADMIN", "NET_RAW"]
    restart: always
  docker-ssh:
    image: panubo/sshd
    environment: 
      - SSH_USERS=jamdev:1001:1001
      - SSH_ENABLE_PASSWORD_AUTH=true
      - TCP_FORWARDING=true
    volumes:
      - "./ssh/bootstrap/:/etc/entrypoint.d/"
    ports:
      - "2222:22"
    labels:
      - "traefik.enable=false"
networks:
  default:
    external:
      name: jamdev
