[global]
  sendAnonymousUsage = false

[log]
  level = "INFO" 
  format = "common"

[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"
    
[api]
  insecure = true
  dashboard = true

[providers]
  [providers.docker]
  endpoint = "tcp://dockerproxy:2375"
  [providers.file]
  directory = "/etc/traefik/dynamic"
  watch = true
